version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Denver"
    groups:
      npm-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
      npm-minor-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "major"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
